version: "3.9"

volumes:
  suricata_logs:

services:
  telegraf:
    build:
      context: ./telegraf
      dockerfile: Dockerfile
    image: custom-telegraf:latest
    container_name: rpi_telegraf
    user: "995:990"
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_ORG=network-monitoring
      - DOCKER_INFLUXDB_INIT_BUCKET=network-data
      - INFLUX_TOKEN=/run/secrets/influx_token
    secrets:
      - influx_token
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf/process_monitor.sh:/usr/local/bin/process_monitor.sh
      - suricata_logs:/var/log/suricata:ro
    depends_on:
      - suricata
      - softflowd
    network_mode: "host"

  suricata:
    build:
      context: ./suricata
      dockerfile: Dockerfile
    image: custom-suricata:latest
    container_name: rpi_suricata
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
    volumes:
      - suricata_logs:/var/log/suricata
      - /var/run/suricata:/var/run/suricata
    command: ["-i", "eth0"]
    restart: unless-stopped

  softflowd:
    build:
      context: ./softflowd
      dockerfile: Dockerfile
    image: custom-soflowd:latest
    container_name: rpi_softflowd
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW

secrets:
  influx_token:
    file: ./secrets/influx_token.txt
