apiVersion: 1
contactPoints:
    - orgId: 1
      name: telegram bot
      receivers:
        - uid: fekrlbqhkhs00b
          type: telegram
          settings:
            bottoken: ${GF_TELEGRAM_BOT_TOKEN}
            chatid: |
                ${GF_TELEGRAM_CHAT_ID}
            disable_notification: false
            disable_web_page_preview: false
            message: |-
                The anomaly was detected⚠️

                Check the dashboard <b>ASAP</b>!

                The details:
            parse_mode: HTML
            protect_content: false
          disableResolveMessage: true