"""moved one column from router table to device table

Revision ID: 0da20ccc126b
Revises: eb5bb6b3571d
Create Date: 2025-02-23 17:02:00.612558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da20ccc126b'
down_revision = 'eb5bb6b3571d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('if_blocked', sa.Boolean(), nullable=False))

    with op.batch_alter_table('router', schema=None) as batch_op:
        batch_op.drop_column('if_blocked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('router', schema=None) as batch_op:
        batch_op.add_column(sa.Column('if_blocked', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('if_blocked')

    # ### end Alembic commands ###
