"""Added anomaly_alerts table

Revision ID: 628d35bdfc5a
Revises: bfeb766a2da7
Create Date: 2025-05-11 22:47:39.259695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628d35bdfc5a'
down_revision = 'bfeb766a2da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('alert_time', sa.DateTime(), nullable=True),
    sa.Column('src_ip', sa.String(length=64), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_ip', sa.String(length=64), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('router_mac', sa.String(length=64), nullable=False),
    sa.Column('router_public_ip', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomaly_alerts')
    # ### end Alembic commands ###
