"""Added last_updated_at columns to public IP detail model

Revision ID: bfeb766a2da7
Revises: db30a2b92fe3
Create Date: 2025-05-11 16:19:51.563513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfeb766a2da7'
down_revision = 'db30a2b92fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_ip_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_ip_details', schema=None) as batch_op:
        batch_op.drop_column('last_updated_at')

    # ### end Alembic commands ###
