"""Added public IP detail model

Revision ID: db30a2b92fe3
Revises: e8367335d8fb
Create Date: 2025-05-04 14:48:25.923343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db30a2b92fe3'
down_revision = 'e8367335d8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_ip_details',
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('organization', sa.String(length=256), nullable=True),
    sa.Column('hostname', sa.String(length=256), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('postal', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_ip_details')
    # ### end Alembic commands ###
