"""Changes to router and device tables, adding ssh access columns

Revision ID: e4452b45f7e7
Revises: b17fee7ab23a
Create Date: 2025-02-23 13:17:11.879235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4452b45f7e7'
down_revision = 'b17fee7ab23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_ip_address', sa.String(length=64), nullable=False))
        batch_op.drop_column('ip_address')

    with op.batch_alter_table('router', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_ip_address', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('local_ip_address', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('ssh_key_file', sa.String(length=64), nullable=False))
        batch_op.drop_column('ip_address')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('router', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.drop_column('ssh_key_file')
        batch_op.drop_column('username')
        batch_op.drop_column('local_ip_address')
        batch_op.drop_column('public_ip_address')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.drop_column('local_ip_address')

    # ### end Alembic commands ###
