"""Initial migration

Revision ID: e8367335d8fb
Revises: 
Create Date: 2025-03-08 13:55:16.307797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8367335d8fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.Column('public_ip_address', sa.String(length=64), nullable=False),
    sa.Column('local_ip_address', sa.String(length=64), nullable=False),
    sa.Column('ssh_username', sa.String(length=64), nullable=False),
    sa.Column('last_seen_online', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(length=64), nullable=False),
    sa.Column('local_ip_address', sa.String(length=64), nullable=False),
    sa.Column('if_blocked', sa.Boolean(), nullable=False),
    sa.Column('last_seen_online', sa.DateTime(), nullable=True),
    sa.Column('router_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    op.drop_table('users')
    op.drop_table('routers')
    # ### end Alembic commands ###
