"""removed one column, added one column for router table

Revision ID: eb5bb6b3571d
Revises: 3d9071f03da9
Create Date: 2025-02-23 16:39:32.878793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5bb6b3571d'
down_revision = '3d9071f03da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('router', schema=None) as batch_op:
        batch_op.add_column(sa.Column('if_blocked', sa.Boolean(), nullable=False))
        batch_op.drop_column('ssh_key_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('router', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ssh_key_file', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
        batch_op.drop_column('if_blocked')

    # ### end Alembic commands ###
